# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Editor (and arguments) to use for the `open-editor` command. The
# following placeholders are defined: * `{file}`: Filename of the file
# to be edited. * `{line}`: Line in which the caret is found in the
# text. * `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
config.bind('gp', 'spawn --userscript qute-lastpass')
config.bind('gL', 'spawn --userscript lpaccount')
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = ['urxvt', '-e', 'vim', '{}']

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '14pt monospace'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = 'Ttyp0'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '14pt monospace'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '14pt monospace'

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = '~/.config/startpage/index.html'

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {
  'aw': 'https://wiki.archlinux.org/index.php?search={}',
  'ghgf': 'https://github.com/groundfloorus/{}',
  'ghw': 'https://github.com/wandy-dev/{}',
  'ghl': 'https://github.com/lukesmithxyz/{}',
  'r': 'https://reddit.com/r/{}',
  'DEFAULT': 'https://google.com/search?q={}'
}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = '~/.config/startpage/index.html'
